services:
  - type: web
    name: mydrugpaddi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HF_API_KEY
        fromSecret: HF_API_KEY
      - key: GEMINI_API_KEY
        fromSecret: GEMINI_API_KEY